### ISSUE TITLE
Include build step for subprojects

### ISSUE THREAD

**Issue by line-o** [joewiz/hsg-project#10]
After https://github.com/eXistSolutions/hsg-shell/pull/106 is merged, it is necessary to include the build step when installing and updating **hsg-shell**.
Currently only `bower install` runs whenever a `bower.json` is found. However, this does not compile the CSS file that is needed in order to style the site.
The decision to use a CSS-Preprocessor, being it less *or* sass, is the reason for this.
Otherwise this has to be done manually.

I would propose to agree on a more automatic process. The hsg-shell project could provide an npm script, for instance `npm start`, that does all of the above.
The hsg-project build script then checks not only for a bower.json but a second marker that will tell it to run npm start (instead). `package.json` will likely give too many false positives as any project dependent on bower includes that file as well.

**Comment by line-o** [comment]
@joewiz an ant build property might be such a marker.
I will prepare the npm start script.

**Comment by joewiz** [comment]
closed by 0353f7d9c90c75baf8d9fc961ab21fd99de91d5b
